"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:#394260)\
$os\
[](fg:#769ff0 bg:#394260)\
$directory\
[](fg:#394260 bg:#769ff0)\
$git_branch\
$git_status\
[](fg:#394260)\
\n$character"""

right_format = """$status$cmd_duration$jobs$python$java$ruby$aws\
[](fg:#394260)\
$username$hostname\
[](fg:#1d2230 bg:#394260)\
$time\
[▓▒░](fg:#1d2230)"""

[os]
disabled = false
style = "fg:#a3aed2 bg:#394260"
format = "[ $symbol ]($style)"

[os.symbols]
Macos = ""
Arch = ""

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 0
truncate_to_repo = false
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = ""
"Pictures" = ""

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[username]
show_always = true
style_user = "fg:#a3aed2 bg:#394260"
style_root = "bold fg:#ff0000 bg:#394260"
format = "[ $user]($style)"
disabled = false

[hostname]
ssh_only = false
style = "fg:#a3aed2 bg:#394260"
format = "[@$hostname ]($style)"
disabled = false

[time]
disabled = false
time_format = "%H:%M"
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[status]
disabled = false
style = "bold red"
format = "[$status ]($style)"

[cmd_duration]
min_time = 3000
style = "yellow"
format = "[$duration ]($style)"

[jobs]
style = "bold blue"

[python]
symbol = ""
style = "fg:#769ff0"
format = "[$symbol $version ]($style)"

[java]
symbol = ""
style = "fg:#769ff0"
format = "[$symbol $version ]($style)"

[ruby]
symbol = ""
style = "fg:#769ff0"
format = "[$symbol $version ]($style)"

[aws]
symbol = ""
style = "fg:#769ff0"
format = "[$symbol $profile ]($style)"
